# agents:check

["agents:check"]
depends = ["agents:*:check"]

# adk-support-agent

["agents:adk-support-agent:build"]
dir = "{{config_root}}"
run = "docker build -f agents/adk-support-agent/Dockerfile -t ghcr.io/kagenti/adk/agents/adk-support-agent:local --load ."

["agents:adk-support-agent:check"]
depends = ["agents:adk-support-agent:check:*"]

["agents:adk-support-agent:check:hadolint"]
run = "hadolint Dockerfile"
sources = ["Dockerfile"]
dir = "{{config_root}}/agents/adk-support-agent"
